post/urls.py
from django.urls import path
from . import views

app_name = 'post'
urlpatterns = [
    path('', views.PostListView.as_view(), name='post-list'),
    path('<int:pk>/details/',views.PostDetailView.as_view(), name="post-detail"),
    path('new/',views.PostAddView.as_view(),name='add-post'),
    path('<int:pk>/update/',views.PostUpdateView.as_view(),name='update-post'),
    path('<int:pk>/delete/',views.PostDeleteView.as_view(),name='delete-post'),
    path('<int:pk>/get-products/',views.GetProductsView.as_view(), name='get-products'),
]

project/urls.py
from django.urls import path, include
from . import views

app_name = 'project'
urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('<int:project_id>/detail/', views.ProjectDetailView.as_view(), name='project-detail'),
    path('create/', views.ProjectCreateView.as_view(), name='create-project'),
    path('<int:pk>/update/', views.ProjectUpdateView.as_view(), name="update-project"),
    path('<int:pk>/delete/', views.ProjectDeleteView.as_view(), name="delete-project"),
    # path('<int:project_id>/posts/', include('post.urls', namespace='post')),
]

project/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=256)
    # slug = models.SlugField(max_length=255)

    def get_absolute_url(self):
        return reverse("project:project-detail", kwargs={"project_id": self.pk})

    def __str__(self):
        return self.name

project/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.base import RedirectView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy

from .models import Project
from post.models import Post

# Create your views here.
class DashboardView(ListView):
    model = Project
    paginate_by = 20
    template_name = 'project/dashboard.html'

# class ProjectDetailView(DetailView):
#     model = Project
#     context_object_name = 'Projects'
#     template_name = 'project/details.html'
    
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['posts'] = Post.objects.filter(project=self.kwargs.get('pk'))
#         return context

class ProjectDetailView(RedirectView):
    pattern_name = 'post:post-list'

class ProjectCreateView(CreateView):
    model = Project
    fields = ['name']
    template_name = 'project/form.html'

class ProjectUpdateView(UpdateView):
    model = Project
    fields = ['name']
    template_name = 'project/form.html'

class ProjectDeleteView(DeleteView):
    model = Project
    success_url = reverse_lazy('project:dashboard')
    template_name = 'project/delete_confirm.html'

project/templates/project/dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard || SEO Tool{% endblock title %}
{% block content %}

<div class="container mt-5">
    
    <div><a href="{% url 'project:create-project' %}" class="btn btn-primary">New Project</a></div>
    <div class='my-2'>Total projects: {{project_list.count}}</div>
    <table class='table'>
        <tr>
            <td>All Projects</td>
            <td width='200px'>Actions</td>
        </tr>
        {% for project in object_list %}
        <tr>
            <td><a href="{% url 'project:project-detail' project.pk %}">{{ project.name }}</a></td>
            <td>
                <a href="{% url 'project:update-project' project.pk %}">Rename</a> |
                <a href="{% url 'project:delete-project' project.pk %}" class="text-danger">Delete</a>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock content %}

project/templates/project/delete_confirm.html
{% extends 'base.html' %}
{% block title %}Comfirm Delete{% endblock title %}
{% block content %}

<div class="container mt-5">
{% include 'project/header.html' %}
<form action="" method="post">
{% csrf_token %}
    <p>Are you sure you want to delete "{{object}}"?</p>
    <input type='submit' value="Confirm" class="btn btn-danger">
</form>
</div>

{% endblock content %}

project/templates/project/details.html
{% extends 'base.html' %}
{% block title %}Project Details{% endblock title %}

{% block content %}
<div class='container mt-5'>
{% include 'project/header.html' %}
<h4>{{ object.name }}</h4>

<a href="{% url 'post:post-list' project_id=object.pk %}" class="btn btn-success">View URLs &gt;</a>


</div>
{% endblock content %}

project/templates/project/form.html
{% extends "base.html" %}
{% block title %}New Project || SEO Tool{% endblock title %}
{% block content %}
{% load bootstrap4 %}

<div class='container mt-5'>
    <form method="post" class='form'>
        {% csrf_token %}
        {% bootstrap_form form form_layout='inline' %}
        {% bootstrap_button content='Save' button_type='submit' %}
    </form>
</div>

{% endblock content %}

project/templates/project/header.html
<div class="my-2">
    <a href="{% url 'project:dashboard' %}" class="btn btn-primary">Dashboard</a>
</div>