post/urls.py
from django.urls import path
from . import views

app_name = 'post'
urlpatterns = [
    path('', views.PostListView.as_view(), name='post-list'),
    path('<int:pk>/details/',views.PostDetailView.as_view(), name="post-detail"),
    path('new/',views.PostAddView.as_view(),name='add-post'),
    path('<int:pk>/update/',views.PostUpdateView.as_view(),name='update-post'),
    path('<int:pk>/delete/',views.PostDeleteView.as_view(),name='delete-post'),
    path('<int:pk>/get-products/',views.GetProductsView.as_view(), name='get-products'),
]

project/urls.py
from django.urls import path, include
from . import views

app_name = 'project'
urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('<int:project_id>/detail/', views.ProjectDetailView.as_view(), name='project-detail'),
    path('create/', views.ProjectCreateView.as_view(), name='create-project'),
    path('<int:pk>/update/', views.ProjectUpdateView.as_view(), name="update-project"),
    path('<int:pk>/delete/', views.ProjectDeleteView.as_view(), name="delete-project"),
    # path('<int:project_id>/posts/', include('post.urls', namespace='post')),
]

post/models.py
from django.db import models
from django.urls.base import reverse
from project.models import Project

# Create your models here.
class Post(models.Model):
    project         = models.ForeignKey(Project, on_delete=models.CASCADE)
    url             = models.URLField(max_length=256)
    title           = models.CharField(max_length=256, blank=True, null=True)
    contents        = models.TextField(blank=True, null=True)
    # html            = models.TextField(default="")
    meta            = models.TextField(blank=True, null=True)
    last_updated    = models.DateTimeField(auto_now=True,null=True)

    class Meta:
        unique_together = ('project','url',)

    def __str__(self):
        return self.url
    
    def get_absolute_url(self):
        # Add project info
        return reverse('post:post-detail', kwargs={'project_id':self.project.pk,'pk': self.pk})

class Product(models.Model):
    name    = models.CharField(max_length=256)
    post    = models.ForeignKey(Post, on_delete=models.CASCADE)

    class Meta:
        ordering = ('name',)
    #     unique_together = ('name','post',)

    def __str__(self):
        return self.name

class InternalLink(models.Model):
    address = models.CharField(max_length=256)
    post    = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.address

class OutboundLink(models.Model):
    address = models.CharField(max_length=256)
    post    = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.address

class ImageAltText(models.Model):
    text    = models.CharField(max_length=256)
    src     = models.URLField(max_length=255,default="")
    post    = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.text
    
    class Meta:
        unique_together = ('post','text')

class H1(models.Model):
    heading = models.CharField(max_length=256)
    post    = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.heading

class H2(models.Model):
    heading = models.CharField(max_length=256)
    post    = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.heading

class H3(models.Model):
    heading = models.CharField(max_length=256)
    post    = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.heading

class H4(models.Model):
    heading = models.CharField(max_length=256)
    post    = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.heading

post/views.py
from django.shortcuts import redirect, render
from django.views.generic import ListView, DetailView
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.db.models.signals import post_save
from collections import Counter, OrderedDict
from math import ceil

from .models import Post, Product, InternalLink, OutboundLink, ImageAltText, H1, H2, H3, H4
from project.models import Project

from .scrapper import SiteScrapper
from .utils import get_plot

# Create your views here.
class PostListView(ListView):
    # paginate_by = 20
    template_name = 'post/post_list.html'

    def get_queryset(self):
        return Post.objects.filter(project__pk=self.kwargs['project_id'])
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project_id = self.kwargs['project_id']
        context['project_id'] = project_id
        context['project_name'] = Project.objects.get(pk=project_id).name

        if self.object_list.count()>0:
            content_lens = [len(post.contents.split()) for post in self.object_list if post.contents is not None]
            if len(content_lens)>0:
                content_len = ceil((sum(content_lens)/len(content_lens))/100*110)
                context['content_len'] = content_len
        headings = dict()
        headings['h1'] = []
        headings['h2'] = []
        headings['h3'] = []
        headings['h4'] = []
        for post in self.object_list:
            headings['h1'].append(H1.objects.filter(post=post.id))
            headings['h2'].append(H2.objects.filter(post=post.id))
            headings['h3'].append(H3.objects.filter(post=post.id))
            headings['h4'].append(H4.objects.filter(post=post.id))
        context['sub_headings'] = headings

        products = Product.objects.filter(post__project=project_id).order_by('-name')
        products_name = Counter([product.name for product in products])
        # products_name = OrderedDict(Counter([product.name for product in products]))
        if len(products_name)>0:
            names = list(products_name.keys())
            product_count = list(products_name.values())
            chart = get_plot(product_count,names,context['project_name'])
            context['chart'] = chart
        return context

class PostDetailView(DetailView):
    model = Post
    template_name = 'post/details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = Product.objects.filter(post=self.object.pk)
        context['internal_links'] = InternalLink.objects.filter(post=self.object.pk)
        context['outbound_links'] = OutboundLink.objects.filter(post=self.object.pk)
        context['image_alt_texts'] = ImageAltText.objects.filter(post=self.object.pk)
        context['h1'] = H1.objects.filter(post=self.object.pk)
        context['h2'] = H2.objects.filter(post=self.object.pk)
        context['h3'] = H3.objects.filter(post=self.object.pk)
        context['h4'] = H4.objects.filter(post=self.object.pk)
        return context

class PostAddView(CreateView):
    model = Post
    fields = ['url']
    template_name = 'post/form.html'

    def form_valid(self, form):
        project = Project.objects.get(pk=self.kwargs.get('project_id'))
        form.instance.project = project
        post = Post.objects.filter(url=form.instance.url)
        if len(post)!=0:
            print("Already have this.")
            return redirect(post[0])
        else:
            return super().form_valid(form)
        

class PostUpdateView(UpdateView):
    model = Post
    fields = ['project','url']
    template_name = 'post/form.html'

class PostDeleteView(DeleteView):
    model = Post
    # success_url = reverse_lazy('post:post-list', kwargs={})
    template_name = 'post/delete_confirm.html'

    def get_success_url(self):
        return reverse_lazy('post:post-list', kwargs={'project_id': self.kwargs['project_id']})
    
def scrapeSite(sender, instance, created, **kwargs):
    if created:
        print("Creating instance")
        Sc = SiteScrapper(instance.url)
        instance.title = Sc.title
        print("Getting contents")
        instance.contents = Sc.review_content
        print("Getting meta data")
        instance.meta = Sc.getMetaDescription()
        instance.save()
        # Internal links
        print("Getting links")
        for link in Sc.internal_links:
            obj = InternalLink(address=link, post=instance)
            obj.save()
        # Outbound links
        for link in Sc.outbound_links:
            obj = OutboundLink(address=link, post=instance)
            obj.save()
        # Image Alt-text
        print("Getting Image-Alt-Text")
        for alt_text in Sc.getImageAltText():
            try:
                obj = ImageAltText( text=alt_text['alt'], 
                                    src=alt_text['src'],
                                    post=instance) 
                obj.save()
            except: pass
        # Sub Headings
        print("Getting Sub-headings")
        subheadings = Sc.getSubHeadings()
        # h1
        for h in subheadings['h1']:
            obj = H1(heading=h, post=instance)
            obj.save()
        # h2
        for h in subheadings['h2']:
            obj = H2(heading=h, post=instance)
            obj.save()
        # h3
        for h in subheadings['h3']:
            obj = H3(heading=h, post=instance)
            obj.save()
        # h4
        for h in subheadings['h4']:
            obj = H4(heading=h, post=instance)
            obj.save()
        print("End scrapping")


post_save.connect(scrapeSite, sender=Post)

class GetProductsView(TemplateView):
    template_name = 'post/get_products.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = Post.objects.get(pk=self.kwargs.get('pk'))
        Sc = SiteScrapper(post.url)
        context['tags'] = Sc.getProducts()
        tagnames = [tag['name'] for tag in context['tags']]
        context['max'] = max(tagnames, key=tagnames.count)
        return context
    
    def post(self, request, *args, **kwargs):
        products = request.POST.getlist('products')
        for product in products:
            obj = Product(name=product,post=Post.objects.get(pk=self.kwargs.get('pk')))
            obj.save()
        return redirect('post:post-detail',project_id=self.kwargs.get('project_id'),pk=self.kwargs.get('pk'))

post/templates/post/delete_confirm.html
{% extends 'base.html' %}
{% block title %}Comfirm Delete{% endblock title %}
{% block content %}

<div class="container mt-5">
{% include 'post/header.html' %}
<form action="" method="post">
{% csrf_token %}
    <p>Are you sure you want to delete "{{object}}"?</p>
    <input type='submit' value="Confirm" class="btn btn-danger">
</form>
</div>

{% endblock content %}

post/templates/post/details.html
{% extends 'base.html' %}
{% block title %}Project Details{% endblock title %}

{% block content %}
<div class='container mt-5'>
{% include 'post/header.html' %}

<h4>Title: {{ object.title }}</h4>
<p>URL: <a href="{{object.url}}" target="_blank">{{object.url}}</a></p>
<p>Last Updated: <i class='text-info'>{{ object.last_updated }}</i></p>

<!-- Keyword Density -->
<div class="input-group mb-3">
    <div class='input-group-prepend'>
        <span class='input-group-text'>Check keyword density</span>
    </div>
    <input name="keyword-input" type="text" class='form-control' id='keyword-input'
    placeholder="Enter keyword" onkeyup="keywordCount()">
    <div class="input-group-append">
       <span id="output" class='input-group-text'>0 entries</span>
    </div>
</div>

<!-- Contents -->
<p><b>Contents:</b> {{object.contents|wordcount}} words
    <button class="btn btn-sm btn-outline-info ml-2" 
        onclick="toggleContent(this,document.getElementById('review-content'))">
    Show &or;</button>
</p>
<p style="display:none" id='review-content'>{{ object.contents }}</p>

<!-- Meta Description -->
<p><b>Meta Description:</b> {{ object.meta|wordcount }} words
    <button class="btn btn-sm btn-outline-info ml-2" 
        onclick="toggleContent(this,document.getElementById('meta'))">
    Show &or;</button>
</p>
<p style="display:none" id='meta'>{{ object.meta }}</p>

<!-- Internal Links -->
<p><b>Internal Links:</b> {{ internal_links.count }} entries
    <button class="btn btn-sm btn-outline-info ml-2" 
        onclick="toggleContent(this,document.getElementById('internal-links'))">
    Show &or;</button>
</p>
<ol style="display:none" id='internal-links'>
{% for link in internal_links %}
    <li>{{link}}</li>
{% endfor %}
</ol>

<!-- Outbound Links -->
<p><b>Outbound Links:</b> {{ outbound_links.count }} entries
    <button class="btn btn-sm btn-outline-info ml-2" 
        onclick="toggleContent(this,document.getElementById('outbound-links'))">
    Show &or;</button>
</p>
<ol style="display:none" id='outbound-links'>
{% for link in outbound_links %}
    <li>{{link}}</li>
{% endfor %}
</ol>

<!-- Image Alternative Texts -->
<p><b>Image Alternative Texts:</b> {{ image_alt_texts.count }} entries
    <button class="btn btn-sm btn-outline-info ml-2" 
        onclick="toggleContent(this,document.getElementById('image-alt-texts'))">
    Show &or;</button>
    <input type="checkbox" id="show-image" class="ml-2"> Show with image
</p>
<table class='table' style="display:none" id='image-alt-texts'>
{% for alt_text in image_alt_texts %}
    <tr>
        <td>{{alt_text.text}}</td>
        <td class="alt-text" style="display:none"><img src="{{alt_text.src}}" width="200" /></td>
    </tr>
{% endfor %}
</table>

<!-- Sub Headings -->
<p><b>Sub Headings:</b> {{ sub_headings.count }} entries
    <!-- h1 -->
    <p><b>h1:</b> {{ h1.count }} entries
        <button class="btn btn-sm btn-outline-info ml-2" 
            onclick="toggleContent(this,document.getElementById('h1'))">
        Show &or;</button>
    </p>
    <ol style="display:none" id='h1'>
    {% for heading in h1 %}
        <li>{{heading}}</li>
    {% endfor %}
    </ol>
<!-- h2 -->
<p><b>h2:</b> {{ h2.count }} entries
    <button class="btn btn-sm btn-outline-info ml-2" 
        onclick="toggleContent(this,document.getElementById('h2'))">
    Show &or;</button>
</p>
<ol style="display:none" id='h2'>
{% for heading in h2 %}
    <li>{{heading}}</li>
{% endfor %}
</ol>
<!-- h3 -->
<p><b>h3:</b> {{ h3.count }} entries
    <button class="btn btn-sm btn-outline-info ml-2" 
        onclick="toggleContent(this,document.getElementById('h3'))">
    Show &or;</button>
</p>
<ol style="display:none" id='h3'>
{% for heading in h3 %}
    <li>{{heading}}</li>
{% endfor %}
</ol>
<!-- h4 -->
<p><b>h4:</b> {{ h4.count }} entries
    <button class="btn btn-sm btn-outline-info ml-2" 
        onclick="toggleContent(this,document.getElementById('h4'))">
    Show &or;</button>
</p>
<ol style="display:none" id='h4'>
{% for heading in h4 %}
    <li>{{heading}}</li>
{% endfor %}
</ol>

{% if products %}
    <p><b>Products</b> {{products.count}} entries<button class="btn btn-sm btn-outline-info ml-2" 
        onclick="toggleContent(this,document.getElementById('products'))">
        Show &or;</button>
    </p>
    <ol style="display:none" id='products'>
    {% for product in products %}
        <li>{{product}}</li>
    {% endfor %}
    </ol>
{% else %}
<a href="{% url 'post:get-products' object.project.pk object.pk %}">Get products</a>
{% endif %}

</div>
<script>
    function toggleContent(btn,content){
        if(content.style.display == "none"){
            content.style.display = "block";
            btn.innerHTML = "Hide &and;";
        } else {
            content.style.display = "none";
            btn.innerHTML = "Show &or;";
        }
    }

    function keywordCount(){
        var str = document.getElementById('review-content').innerHTML;
        var keyword = document.getElementById('keyword-input').value;
        var output = document.getElementById('output');
        var re = new RegExp(keyword,"gi");
        if(keyword==""){
            count = 0
        } else {
            count = str.match(re).length;
        }
        output.innerHTML = count + " entries"
    }

    $("#show-image").change(function(){
        if($("td.alt-text").css("display") == "none"){
            $("td.alt-text").css("display","");
        } else {
            $("td.alt-text").css("display","none");
        }
    });
</script>
{% endblock content %}

post/templates/post/form.html
{% extends "base.html" %}
{% block title %}New Project || SEO Tool{% endblock title %}
{% block content %}
{% load bootstrap4 %}

<div class='container mt-5'>
    <form method="post" class='form'>
        {% csrf_token %}
        {% bootstrap_form form form_layout='inline' %}
        {% bootstrap_button content='Save' button_type='submit' %}
    </form>
    <div class="my-5" style="display:none" id="progress-bar">
        <div class="text-center">Getting Data ...</div>
        <div class="progress">
            <div class="progress-bar progress-bar-striped progress-bar-animated"
            role='progressbar' aria-valuenow='100' aria-valuemin='0' aria-valuemax='100'
            style="width:100%"></div>
        </div>
    </div>
</div>

<script>
    $("button[type='submit']").click(function(){
        $("#progress-bar").css('display','');
    });
</script>

{% endblock content %}

post/templates/post/get_products.html
{% extends 'base.html' %}
{% block title %}Get Products{% endblock title %}
{% block content %}

<div class='container my-5'>
    <div class='mb-3'>
        <button id='select-similar' class='btn btn-outline-primary'>Select Similar</button>
        <button id='select-all' class='btn btn-outline-primary'>Select All</button>
        <button id='deselect-all' class='btn btn-outline-primary'>Deselect All</button>
    </div>
    <form method='post'>
        {% csrf_token %}
        {% for tag in tags %}
        <div class="form-check">
            <input type="checkbox" value="{{tag.content}}" name="products" 
            class="form-check-input" classlist={{tag.class|default:"None"}} 
            tagname={{tag.name}}>
            <label class="form-check-label">{{tag.content}}</label>
        </div>
        {% endfor %}
        <input type='submit' value='Add to Products' 
        class='btn btn-outline-primary mt-2'>
    </form>
</div>

<script>
    /* Auto Select
    products = $("input[classlist*='product']");
    if(products.length>0){
        products.each(function(){
            $(this).prop('checked',true);
        });
    } else {
        $('input[tagname={{max}}]').each(function(){
            $(this).prop('checked',true);
        });
    }*/
    // Select Similar
    $('#select-similar').click(function(){
        var selected = [];
        $('input:checked').each(function(){
            var tagname = $(this).attr('tagname')
            if(tagname && selected.indexOf(tagname)==-1){
                if($(this).attr('classname') != 'None'){
                    var classname = $(this).attr('classlist')
                    tag = {'name':tagname, 'class':classname}
                } else {
                    tag = {'name':tagname}
                }
                selected.push(tag);
            }
        });
        selected.forEach(function(tag){
            $('input[tagname='+tag['name']+'][classlist='+tag['class']+']').each(function(){
                $(this).prop('checked',true);
            });
        });
    });
    // Select All
    $('#select-all').click(function(){
        $('input[type=checkbox]').each(function(){
            $(this).prop('checked',true);
        });
    });
    // Deselect All
    $('#deselect-all').click(function(){
        $('input:checked').each(function(){
            $(this).prop('checked',false);
        });
    });
</script>

{% endblock content %}

post/templates/post/header.html
<div class="my-2">
    <a href="{% url 'post:post-list' object.project.pk %}" class="btn btn-primary">&lt; Project Details</a>
</div>

post/templates/post/post_list.html
{% extends "base.html" %}
{% block title %}Blog posts{% endblock title %}
{% block content %}

<div class="container my-5">
    
    <div class='mb-2'>
        <a href="{% url 'project:dashboard' %}" class="btn btn-primary">&lt; Dashboard</a>
        <a href="{% url 'post:add-post' project_id %}" class="btn btn-primary">Add Blog Post</a>
    </div>
    <h4>{{project_name}}</h4>
    <div class='my-2'>Total blog posts: {{object_list.count}}</div>
    <table class='table'>
        {% for post in object_list %}
        <tr>
            <td>
                <a href="{% url 'post:post-detail' project_id post.pk %}">
                    {{ post.title }}<br>
                    {{ post.url }}
                </a>
            </td>
            <td>
                <a href="{% url 'post:delete-post' project_id post.pk %}" class="text-danger">Delete</a>
            </td>
        </tr>
        {% endfor %}
    </table>
    <h3 class="text-success">Report</h3>
    <div>
        {% if content_len %}
        <h4>Suggested Content Length: {{content_len}} words</h4>
        {% endif %}

        <!-- Headings -->
        <!-- H1 -->
        {% if object_list %}
        <h4>Subheadings</h4>
        <table class="table table-sm table-bordered">
            <thead class='thead-light'>
                <tr>
                <th>Tag</th>
                    {% for post in object_list %}
                    <th>{{post.url}}</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for key,value in sub_headings.items %}
                    <tr>
                        <td>{{key}}</td>
                        {% for list in value %}
                        <td><ul>{% for h in list %}<li>{{h.heading}}</li>{% endfor %}</ul></td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
            <h1 class='display-3 text-center border rounded p-5 m-5'>No site scrapped yet!</h1>
        {% endif %}
    </div>

    {% if chart %}
    <div>
        <h4>Products</h4>
        <img src="data:image/png;base64, {{chart|safe}}" class="img-fluid"/>
    </div>
    {% endif %}
    
</div>

{% endblock content %}